"""Normalisierungs-Library: kanonisches Schema als einzige Quelle der Wahrheit.

Re-exportiert die öffentliche API der Library (CORE-01): den
``CanonicalRecord``-Envelope, die Wert-Objekte, die Lizenz-/Quellen-Enums sowie
die diskriminierte Payload-Union und ihre Mitglieder. Jede Quelle ab Phase 4
bildet ihre Daten auf diese Modelle ab.
"""

from __future__ import annotations

from cityscape.normalization.enums import LicenseId, LicenseTier, SourceId
from cityscape.normalization.models import (
    SCHEMA_VERSION,
    Attribution,
    CanonicalRecord,
    GeoPoint,
)
from cityscape.normalization.payloads import (
    AccidentPayload,
    AdminBoundaryPayload,
    AirQualityPayload,
    BathingWaterPayload,
    BusinessRegistrationsPayload,
    ChargingStationPayload,
    ChargingStatusCityPayload,
    ChargingStatusPayload,
    CityBaseDataPayload,
    CivilProtectionWarningPayload,
    CountStationPayload,
    CrimeStatsPayload,
    DemographicsPayload,
    DistrictHeatingPayload,
    ElectionResultPayload,
    EnergyAssetPayload,
    EventPayload,
    FireDangerPayload,
    FloodWarningPayload,
    FuelPricePayload,
    HolidayPayload,
    HospitalAtlasPayload,
    HospitalPayload,
    IcuCapacityPayload,
    IndicatorsPayload,
    InsolvenciesPayload,
    LandValuesPayload,
    OfficeWaitTimesPayload,
    ParkingPayload,
    PayloadUnion,
    PoiPayload,
    PollenUvPayload,
    PopulationDensityPayload,
    PowerPayload,
    PublicTenderPayload,
    RegionalStatPayload,
    RoadEventPayload,
    SharingPayload,
    SolarPayload,
    SolarRoofsPayload,
    StationArrivalsPayload,
    StationCatalogPayload,
    StationDeparturesPayload,
    StationFacilityPayload,
    TaxRatesPayload,
    TrafficEventPayload,
    TrafficFlowPayload,
    TransitStopPayload,
    VehicleRegistrationPayload,
    WaterLevelPayload,
    WeatherPayload,
    WeatherWarningPayload,
    WebcamPayload,
)

__all__ = [
    "SCHEMA_VERSION",
    "AccidentPayload",
    "AdminBoundaryPayload",
    "AirQualityPayload",
    "Attribution",
    "BathingWaterPayload",
    "BusinessRegistrationsPayload",
    "CanonicalRecord",
    "ChargingStationPayload",
    "ChargingStatusCityPayload",
    "ChargingStatusPayload",
    "CityBaseDataPayload",
    "CivilProtectionWarningPayload",
    "CountStationPayload",
    "CrimeStatsPayload",
    "DemographicsPayload",
    "DistrictHeatingPayload",
    "ElectionResultPayload",
    "EnergyAssetPayload",
    "EventPayload",
    "FireDangerPayload",
    "FloodWarningPayload",
    "FuelPricePayload",
    "GeoPoint",
    "HolidayPayload",
    "HospitalAtlasPayload",
    "HospitalPayload",
    "IcuCapacityPayload",
    "IndicatorsPayload",
    "InsolvenciesPayload",
    "LandValuesPayload",
    "LicenseId",
    "LicenseTier",
    "OfficeWaitTimesPayload",
    "ParkingPayload",
    "PayloadUnion",
    "PoiPayload",
    "PollenUvPayload",
    "PopulationDensityPayload",
    "PowerPayload",
    "PublicTenderPayload",
    "RegionalStatPayload",
    "RoadEventPayload",
    "SharingPayload",
    "SolarPayload",
    "SolarRoofsPayload",
    "SourceId",
    "StationArrivalsPayload",
    "StationCatalogPayload",
    "StationDeparturesPayload",
    "StationFacilityPayload",
    "TaxRatesPayload",
    "TrafficEventPayload",
    "TrafficFlowPayload",
    "TransitStopPayload",
    "VehicleRegistrationPayload",
    "WaterLevelPayload",
    "WeatherPayload",
    "WeatherWarningPayload",
    "WebcamPayload",
]
